import asyncio, random, discord

from discord.ext import commands

nicks = [
  "Ombra Ammantata",
  "Disco Diva",
  "Calcafiamma",
  "Lapilla",
  "Spezzacuori",
  "Istinto",
  "Cornetto",
  "Nara",
  "Paradosso",
  "Ribelle",
  "Rivolta",
  "Mortafiamma",
  "Acchiappamosche",
  "Leviatano",
  "Anfibio Acquatico",
  "Corvo",
  "Cavaliere Rosso",
  "Avanguardia Oscura",
  "Accordo Potente",
  "Rapace",
  "Presagio",
  "Destino",
  "Criterio",
  "Oblivion",
  "Vertex",
  "Ravage",
  "Valkiria",
  "Jolly",
  "Elmira",
  "Castore",
  "Soldato Nevischio",
  "Taro",
  "Frittella",
  "Ringhio",
  "Archetipo",
  "Furfante",
  "Ventura",
  "Bandoliera",
  "Testa di Pomodoro",
  "Truppa Tossica",
  "Agente Biologico",
  "Artigliere Lucente",
  "Artigliere Lucente",
  "Bianco Accecante",
  "Spaziale",
  "Chirurgo da Campo",
  "Spaventapasseri",
  "Infestazione",
  "Operazione Paglia",
  "Jack Gourdon",
  "Manzo Boss",
  "Falena Commando",
  "Tenero Difensore",
  "Bombardiere Oscuro",
  "Dynamo",
  "Pescesecco",
  "Zero Assoluto",
  "Assassino Artico",
  "Bombarolo Lucente",
  "Asso Alpino",
  "Cuorenero",
  "Ibrido",
  "Bananita",
  "Lusso",
  "Trog",
  "Re dei Ghiacci",
  "Calamity",
  "DJ Yonder",
  "Fiaba",
  "Tramonto",
  "Cacciatrice",
  "Alla Deriva",
  "Linea Rossa",
  "Soccorso in Corsa",
  "Mazza",
  "Torre",
  "Ragnarok",
  "Carburo",
  "Teknica",
  "Zoey",
  "Valore",
  "Omega",
  "Visitatore",
  "Agente Élite",
  "Il Mietitore",
  "Cavaliere Blu",
  "Cavaliere Reale",
  "Cavaliere Nero",
  "Incursore Rinnegato",
  "Coniglio Mastino",
  "Coniglio Incursore",
  "Trifoglio Verde",
  "Wukong",
  "Schiaccianoci",
  "Milite Teschio",
  "Milite Ghoul",
  "Agente Ribelle",
  "Asso",
  "Bombardiere Reale",
  "Percussore Blu",
  "Pioniere",
  "Subcomandante",
  "Galassia",
  "Frostbite",
  "Riflesso",
  "Aura",
  "Calzamaglia",
  "Specialista di Missioni",
  "Signore della Ruggine",
  "Camminatore Lunare",
  "Viaggiatore Oscuro",
  "Milite Assalto Aereo",
  "Segugio da Guerra",
  "Difensore Scarlatto",
  "Ranger dell’Amore",
  "Saccheggiatore Felice",
  "Artigliere allo Zenzero",
  "Percussore Sommitale",
  "Havoc",
  "Doppia Elica",
  "Mayhem",
  "Tiro Preciso",
  "Intuizione",
  "Grimbles",
  "Recon Scout",
  "Pressofuso",
  "Cipher",
  "Brawler",
  "Spina Dorsale",
  "Sanctum",
  "Heidi",
  "Milite Triage",
  "Hacivat",
  "Stella Ammantata",
  "Bubù Settete",
  "Scatenata",
  "Ciuffo Predone",
  "Assassino Aerobico",
  "Vista D’Acciaio",
  "Operazione Segreta",
  "Abstrakt"
]

class RandomNickPlugin(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.command(aliases=["random"])
    @commands.guild_only()
    @commands.has_permissions(manage_nicknames=True)
    async def randomnick(self, ctx, *, user: discord.Member):
        """Assegna un nickname casuale all'utente"""
        randomnick = random.choice(nicks)
        try:
            await user.edit(nick=randomnick)
            await ctx.send(f":crayon: Il nuovo nome generato casualmente per **{user.name}** è **{randomnick}**.")
        except:
            await ctx.send(f":crayon: Non riesco a generare casualmente un soprannome per **{user.name}**.")

async def setup(bot):
    await bot.add_cog(RandomNickPlugin(bot))
